#!/bin/bash
# Updated: April 28, 2026
/data/.openclaw/workspace/cloudflared tunnel run --token eyJhIjoiZWFkZmE0MTc0Y2VjYzAyYjJiOGQwN2Y5YTdkYmFlMzkiLCJ0IjoiNDE5MGZlZTMtOGYzOS00NTMxLTk4ZmUtNGFjYzUzN2FlOWU1IiwicyI6Ik5UazBObVEwTldFdFpERXlNeTAwWXpKakxXRmxNV1l0WW1RME5HTTFNV1kwWlRaaiJ9